package runtime

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ateam/defaults"
)

// Toolchain represents a detected project toolchain and the Dockerfile
// instructions needed to install it.
type Toolchain struct {
	Name     string   // e.g. "go", "rust", "python"
	Packages []string // apt packages to install
	RunLines []string // raw Dockerfile RUN lines (for non-apt installs like rustup)
}

// toolchainRule maps a marker file to its toolchain.
type toolchainRule struct {
	Marker    string
	Toolchain Toolchain
}

// goVersion reads the Go version from go.mod (e.g. "1.25.0" → "1.25.0").
// Falls back to "1.23.0" if the file can't be parsed.
func goVersion(sourceDir string) string {
	f, err := os.Open(filepath.Join(sourceDir, "go.mod"))
	if err != nil {
		return "1.23.0"
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if strings.HasPrefix(line, "go ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "go "))
		}
	}
	return "1.23.0"
}

// goInstallLines returns Dockerfile RUN lines to install Go from the official tarball.
func goInstallLines(version string) []string {
	return []string{
		fmt.Sprintf(`RUN curl -fsSL https://go.dev/dl/go%s.linux-amd64.tar.gz | tar -C /usr/local -xz`, version),
		`ENV PATH="/usr/local/go/bin:${PATH}"`,
	}
}

var toolchainRules = []toolchainRule{
	// Go is handled specially via goVersion() — see DetectToolchains.
	{"go.mod", Toolchain{Name: "go"}},
	{"Cargo.toml", Toolchain{
		Name: "rust",
		RunLines: []string{
			`RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y` +
				` && echo 'source $HOME/.cargo/env' >> /etc/profile.d/cargo.sh`,
		},
	}},
	{"requirements.txt", Toolchain{Name: "python", Packages: []string{"python3-venv"}}},
	{"pyproject.toml", Toolchain{Name: "python", Packages: []string{"python3-venv"}}},
	{"setup.py", Toolchain{Name: "python", Packages: []string{"python3-venv"}}},
	{"Pipfile", Toolchain{Name: "python", Packages: []string{"python3-venv"}}},
	{"pom.xml", Toolchain{Name: "java", Packages: []string{"default-jdk"}}},
	{"build.gradle", Toolchain{Name: "java", Packages: []string{"default-jdk"}}},
	{"build.gradle.kts", Toolchain{Name: "java", Packages: []string{"default-jdk"}}},
	{"Gemfile", Toolchain{Name: "ruby", Packages: []string{"ruby-full"}}},
	{".ruby-version", Toolchain{Name: "ruby", Packages: []string{"ruby-full"}}},
}

// DetectToolchains scans sourceDir for marker files and returns the
// toolchains needed by the project. Each toolchain appears at most once.
func DetectToolchains(sourceDir string) []Toolchain {
	seen := map[string]bool{}
	var result []Toolchain
	for _, rule := range toolchainRules {
		if seen[rule.Toolchain.Name] {
			continue
		}
		if _, err := os.Stat(filepath.Join(sourceDir, rule.Marker)); err == nil {
			seen[rule.Toolchain.Name] = true
			tc := rule.Toolchain
			// Go needs dynamic version detection from go.mod
			if tc.Name == "go" {
				tc.RunLines = goInstallLines(goVersion(sourceDir))
			}
			result = append(result, tc)
		}
	}
	return result
}

// ReadBaseDockerfile reads the base Dockerfile content, skipping .ateam/Dockerfile.
// Fallback: .ateamorg/Dockerfile → .ateamorg/defaults/Dockerfile → embedded.
func ReadBaseDockerfile(orgDir string) ([]byte, error) {
	if orgDir != "" {
		for _, rel := range []string{"Dockerfile", "defaults/Dockerfile"} {
			path := filepath.Join(orgDir, rel)
			if data, err := os.ReadFile(path); err == nil {
				return data, nil
			}
		}
	}
	data, err := defaults.FS.ReadFile("Dockerfile")
	if err != nil {
		return nil, fmt.Errorf("no base Dockerfile found: %w", err)
	}
	return data, nil
}

// GenerateDockerfile takes a base Dockerfile and inserts toolchain install
// instructions before the first USER directive. If no USER directive is found,
// the block is appended at the end.
func GenerateDockerfile(base []byte, toolchains []Toolchain) []byte {
	if len(toolchains) == 0 {
		return base
	}

	// Build the install block
	var names []string
	var aptPkgs []string
	var extraRuns []string
	for _, tc := range toolchains {
		names = append(names, tc.Name)
		aptPkgs = append(aptPkgs, tc.Packages...)
		extraRuns = append(extraRuns, tc.RunLines...)
	}

	var block strings.Builder
	block.WriteString(fmt.Sprintf("# --- auto-generated by ateam: detected %s ---\n", strings.Join(names, ", ")))
	if len(aptPkgs) > 0 {
		block.WriteString("RUN apt-get update && apt-get install -y --no-install-recommends \\\n")
		for _, pkg := range aptPkgs {
			block.WriteString(fmt.Sprintf("    %s \\\n", pkg))
		}
		block.WriteString("    && rm -rf /var/lib/apt/lists/*\n")
	}
	for _, run := range extraRuns {
		block.WriteString(run + "\n")
	}
	block.WriteString("# --- end auto-generated ---\n")

	lines := strings.Split(string(base), "\n")
	var out strings.Builder
	inserted := false
	for _, line := range lines {
		if !inserted && strings.HasPrefix(strings.TrimSpace(line), "USER ") {
			out.WriteString("\n")
			out.WriteString(block.String())
			out.WriteString("\n")
			inserted = true
		}
		out.WriteString(line + "\n")
	}
	if !inserted {
		out.WriteString("\n")
		out.WriteString(block.String())
	}

	// strings.Split + "\n" join adds a trailing newline; trim to single
	result := strings.TrimRight(out.String(), "\n") + "\n"
	return []byte(result)
}

// AutoSetupDockerfile generates .ateam/Dockerfile if it doesn't exist and
// project toolchains are detected. Returns whether a file was generated and
// the names of detected toolchains.
func AutoSetupDockerfile(sourceDir, projectDir, orgDir string) (bool, []string, error) {
	target := filepath.Join(projectDir, "Dockerfile")
	if _, err := os.Stat(target); err == nil {
		return false, nil, nil // already exists
	}

	toolchains := DetectToolchains(sourceDir)
	if len(toolchains) == 0 {
		return false, nil, nil
	}

	base, err := ReadBaseDockerfile(orgDir)
	if err != nil {
		return false, nil, err
	}

	result := GenerateDockerfile(base, toolchains)

	if err := os.MkdirAll(projectDir, 0755); err != nil {
		return false, nil, fmt.Errorf("mkdir %s: %w", projectDir, err)
	}
	if err := os.WriteFile(target, result, 0644); err != nil {
		return false, nil, fmt.Errorf("write %s: %w", target, err)
	}

	names := make([]string, len(toolchains))
	for i, tc := range toolchains {
		names[i] = tc.Name
	}
	return true, names, nil
}
