package runtime

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDetectToolchains(t *testing.T) {
	dir := t.TempDir()

	// No markers → no toolchains
	tc := DetectToolchains(dir)
	if len(tc) != 0 {
		t.Fatalf("expected 0 toolchains, got %d", len(tc))
	}

	// Add go.mod and requirements.txt
	os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module test\n\ngo 1.25.0\n"), 0644)
	os.WriteFile(filepath.Join(dir, "requirements.txt"), []byte("flask"), 0644)

	tc = DetectToolchains(dir)
	if len(tc) != 2 {
		t.Fatalf("expected 2 toolchains, got %d", len(tc))
	}
	if tc[0].Name != "go" {
		t.Errorf("expected first toolchain 'go', got %q", tc[0].Name)
	}
	if tc[1].Name != "python" {
		t.Errorf("expected second toolchain 'python', got %q", tc[1].Name)
	}
}

func TestDetectToolchains_Dedup(t *testing.T) {
	dir := t.TempDir()

	// Multiple python markers should produce only one toolchain
	os.WriteFile(filepath.Join(dir, "requirements.txt"), []byte(""), 0644)
	os.WriteFile(filepath.Join(dir, "pyproject.toml"), []byte(""), 0644)

	tc := DetectToolchains(dir)
	if len(tc) != 1 {
		t.Fatalf("expected 1 toolchain (deduped), got %d", len(tc))
	}
	if tc[0].Name != "python" {
		t.Errorf("expected 'python', got %q", tc[0].Name)
	}
}

func TestGenerateDockerfile_InsertsBeforeUSER(t *testing.T) {
	base := []byte("FROM node:20\nRUN echo hi\nUSER agent\nWORKDIR /app\n")
	toolchains := []Toolchain{
		{Name: "go", RunLines: []string{
			"RUN curl -fsSL https://go.dev/dl/go1.25.0.linux-amd64.tar.gz | tar -C /usr/local -xz",
			`ENV PATH="/usr/local/go/bin:${PATH}"`,
		}},
	}

	result := string(GenerateDockerfile(base, toolchains))

	// The install block should appear before USER
	userIdx := strings.Index(result, "USER agent")
	blockIdx := strings.Index(result, "# --- auto-generated by ateam")
	if blockIdx < 0 {
		t.Fatal("auto-generated block not found")
	}
	if blockIdx >= userIdx {
		t.Error("auto-generated block should appear before USER directive")
	}

	// Should contain the Go install
	if !strings.Contains(result, "go1.25.0.linux-amd64") {
		t.Error("expected Go tarball install in output")
	}

	// USER and WORKDIR should still be present
	if !strings.Contains(result, "USER agent") {
		t.Error("USER directive missing from output")
	}
	if !strings.Contains(result, "WORKDIR /app") {
		t.Error("WORKDIR directive missing from output")
	}
}

func TestGenerateDockerfile_NoUSER(t *testing.T) {
	base := []byte("FROM node:20\nRUN echo hi\n")
	toolchains := []Toolchain{
		{Name: "python", Packages: []string{"python3-venv"}},
	}

	result := string(GenerateDockerfile(base, toolchains))
	if !strings.Contains(result, "python3-venv") {
		t.Error("expected 'python3-venv' package in output")
	}
	if !strings.Contains(result, "# --- end auto-generated ---") {
		t.Error("expected end marker")
	}
}

func TestGenerateDockerfile_NoToolchains(t *testing.T) {
	base := []byte("FROM node:20\n")
	result := GenerateDockerfile(base, nil)
	if string(result) != string(base) {
		t.Error("expected unchanged base when no toolchains")
	}
}

func TestGenerateDockerfile_RustRunLines(t *testing.T) {
	base := []byte("FROM node:20\nUSER agent\n")
	toolchains := []Toolchain{
		{Name: "rust", RunLines: []string{"RUN curl https://rustup.rs | sh"}},
	}

	result := string(GenerateDockerfile(base, toolchains))
	if !strings.Contains(result, "curl https://rustup.rs") {
		t.Error("expected rustup RUN line")
	}
}

func TestAutoSetupDockerfile_Idempotent(t *testing.T) {
	sourceDir := t.TempDir()
	projectDir := filepath.Join(t.TempDir(), ".ateam")
	os.MkdirAll(projectDir, 0755)

	os.WriteFile(filepath.Join(sourceDir, "go.mod"), []byte("module test\n\ngo 1.25.0\n"), 0644)

	// First call generates
	generated, names, err := AutoSetupDockerfile(sourceDir, projectDir, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !generated {
		t.Error("expected file to be generated")
	}
	if len(names) != 1 || names[0] != "go" {
		t.Errorf("expected [go], got %v", names)
	}

	// Verify file exists and contains Go install
	data, err := os.ReadFile(filepath.Join(projectDir, "Dockerfile"))
	if err != nil {
		t.Fatalf("cannot read generated Dockerfile: %v", err)
	}
	if !strings.Contains(string(data), "go.dev/dl/go") {
		t.Error("generated Dockerfile should contain Go tarball install")
	}

	// Second call skips
	generated, _, err = AutoSetupDockerfile(sourceDir, projectDir, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if generated {
		t.Error("expected skip on second call (idempotent)")
	}
}

func TestAutoSetupDockerfile_NoToolchains(t *testing.T) {
	sourceDir := t.TempDir() // empty dir
	projectDir := filepath.Join(t.TempDir(), ".ateam")

	generated, _, err := AutoSetupDockerfile(sourceDir, projectDir, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if generated {
		t.Error("expected no generation when no toolchains detected")
	}
}

func TestReadBaseDockerfile_Embedded(t *testing.T) {
	data, err := ReadBaseDockerfile("")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(string(data), "FROM") {
		t.Error("expected FROM directive in embedded Dockerfile")
	}
}

func TestReadBaseDockerfile_OrgDir(t *testing.T) {
	orgDir := t.TempDir()
	content := []byte("FROM custom:latest\nRUN echo custom\n")
	os.WriteFile(filepath.Join(orgDir, "Dockerfile"), content, 0644)

	data, err := ReadBaseDockerfile(orgDir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if string(data) != string(content) {
		t.Error("expected org Dockerfile content")
	}
}
