package cmd

import (
	"fmt"
	"strings"

	"github.com/ateam/internal/config"
	"github.com/ateam/internal/prompts"
	"github.com/spf13/cobra"
)

var (
	rolesEnabled   bool
	rolesAvailable bool
	rolesDocs      bool
)

var rolesCmd = &cobra.Command{
	Use:   "roles",
	Short: "List roles for the current project",
	Long: `List roles configured for the current project.

By default (--available), shows all known roles with their status.
With --enabled, shows only enabled roles.
With --docs, generates markdown documentation for all built-in roles.

Example:
  ateam roles
  ateam roles --enabled
  ateam roles --docs > ROLES.md`,
	Args: cobra.NoArgs,
	RunE: runRoles,
}

func init() {
	rolesCmd.Flags().BoolVar(&rolesEnabled, "enabled", false, "list enabled roles only")
	rolesCmd.Flags().BoolVar(&rolesAvailable, "available", false, "list all roles with status (default)")
	rolesCmd.Flags().BoolVar(&rolesDocs, "docs", false, "generate markdown documentation for built-in roles")
}

func runRoles(cmd *cobra.Command, args []string) error {
	if rolesDocs {
		return printRolesDocs()
	}

	env, err := resolveEnv()
	if err != nil {
		return err
	}

	var configRoles map[string]string
	if env.Config != nil {
		configRoles = env.Config.Roles
	}
	allKnown := prompts.AllKnownRoleIDs(configRoles, env.ProjectDir, env.OrgDir)
	if len(allKnown) == 0 {
		fmt.Println("No roles available.")
		return nil
	}

	if rolesEnabled {
		var enabled []string
		for _, name := range allKnown {
			if roleStatus(configRoles, name) == config.RoleEnabled {
				enabled = append(enabled, name)
			}
		}
		if len(enabled) == 0 {
			fmt.Println("No enabled roles.")
			return nil
		}
		for _, name := range enabled {
			fmt.Println(name)
		}
		return nil
	}

	w := newTable()
	fmt.Fprintln(w, "ROLE\tSTATUS\tFLAGS\tDESCRIPTION")
	for _, name := range allKnown {
		meta := prompts.RoleMeta(name)
		fmt.Fprintf(w, "%s\t%s\t%s\t%s\n", name, roleStatus(configRoles, name), roleFlags(meta), meta.Description)
	}
	w.Flush()

	return nil
}

// roleFlags renders the legacy/deprecated frontmatter flags for a role as a
// comma-separated string ("legacy", "deprecated", "legacy,deprecated", or
// empty). Used by `ateam roles` to surface the same signals that drive the
// `--docs` filter so users see why a legacy role doesn't appear in ROLES.md.
func roleFlags(meta prompts.RoleMetadata) string {
	var flags []string
	if meta.Legacy {
		flags = append(flags, "legacy")
	}
	if meta.Deprecated {
		flags = append(flags, "deprecated")
	}
	return strings.Join(flags, ",")
}

// roleStatus reports the effective enabled/disabled status of a role.
// Roles are opt-in: a role is "on" only if configRoles explicitly lists it as
// "on" or "enabled". Anything else — unlisted, "off", or an unrecognized
// status — is "off".
func roleStatus(configRoles map[string]string, name string) string {
	if config.IsRoleEnabled(configRoles[name]) {
		return config.RoleEnabled
	}
	return config.RoleDisabled
}

func printRolesDocs() error {
	defaultCfg := config.DefaultConfig()

	var b strings.Builder
	b.WriteString("# ATeam Built-in Roles\n\n")
	b.WriteString("Generated by `ateam roles --docs`. Roles marked **deprecated** still work but are slated for removal. Legacy roles (predecessors superseded by a dotted replacement) are hidden from this list and only accessible by explicit name.\n\n")
	b.WriteString("| Role | Default | Description | Prompt |\n")
	b.WriteString("|------|---------|-------------|--------|\n")
	for _, id := range prompts.AllRoleIDs {
		meta := prompts.RoleMeta(id)
		if meta.Legacy {
			continue
		}
		status := "off"
		if config.IsRoleEnabled(defaultCfg.Roles[id]) {
			status = "on"
		}
		desc := escapeTableCell(meta.Description)
		if meta.Deprecated {
			desc = "**Deprecated.** " + desc
		}
		link := fmt.Sprintf("[prompt](defaults/roles/%s/report_prompt.md)", id)
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", id, status, desc, link)
	}

	fmt.Print(b.String())
	return nil
}

// escapeTableCell escapes characters that would corrupt a markdown table row.
// A literal `|` in a description splits the cell across columns; backslash-
// escape it. Newlines are flattened to spaces for the same reason.
func escapeTableCell(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.ReplaceAll(s, "|", `\|`)
}
