package cmd

import (
	"fmt"
	"sort"
	"strings"

	"github.com/ateam/internal/config"
	"github.com/ateam/internal/prompts"
	"github.com/ateam/internal/root"
	"github.com/spf13/cobra"
)

var (
	rolesEnabled   bool
	rolesAvailable bool
	rolesDocs      bool
)

var rolesCmd = &cobra.Command{
	Use:   "roles",
	Short: "List roles for the current project",
	Long: `List roles configured for the current project.

By default (--available), shows all known roles with their status.
With --enabled, shows only enabled roles.
With --docs, generates markdown documentation for all built-in roles.

Example:
  ateam roles
  ateam roles --enabled
  ateam roles --docs > ROLES.md`,
	Args: cobra.NoArgs,
	RunE: runRoles,
}

func init() {
	rolesCmd.Flags().BoolVar(&rolesEnabled, "enabled", false, "list enabled roles only")
	rolesCmd.Flags().BoolVar(&rolesAvailable, "available", false, "list all roles with status (default)")
	rolesCmd.Flags().BoolVar(&rolesDocs, "docs", false, "generate markdown documentation for built-in roles")
}

func runRoles(cmd *cobra.Command, args []string) error {
	if rolesDocs {
		return printRolesDocs()
	}

	env, err := root.Resolve(orgFlag, projectFlag)
	if err != nil {
		return err
	}

	if env.Config == nil || len(env.Config.Roles) == 0 {
		fmt.Println("No roles configured.")
		return nil
	}

	if rolesEnabled {
		roles := env.Config.EnabledRoles()
		if len(roles) == 0 {
			fmt.Println("No enabled roles.")
			return nil
		}
		for _, name := range roles {
			fmt.Println(name)
		}
		return nil
	}

	// Default: --available — all roles with status
	var names []string
	for name := range env.Config.Roles {
		names = append(names, name)
	}
	sort.Strings(names)

	w := newTable()
	fmt.Fprintln(w, "ROLE\tSTATUS\tDESCRIPTION")
	for _, name := range names {
		desc := prompts.RoleDescription(name)
		fmt.Fprintf(w, "%s\t%s\t%s\n", name, env.Config.Roles[name], desc)
	}
	w.Flush()

	return nil
}

func printRolesDocs() error {
	defaultCfg := config.DefaultConfig()

	var b strings.Builder
	b.WriteString("# ATeam Built-in Roles\n\n")
	b.WriteString("Generated by `ateam roles --docs`.\n\n")
	b.WriteString("| Role | Default | Description | Prompt |\n")
	b.WriteString("|------|---------|-------------|--------|\n")
	for _, id := range prompts.AllRoleIDs {
		status := "off"
		if config.IsRoleEnabled(defaultCfg.Roles[id]) {
			status = "on"
		}
		desc := prompts.RoleDescription(id)
		link := fmt.Sprintf("[prompt](defaults/roles/%s/report_prompt.md)", id)
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", id, status, desc, link)
	}

	fmt.Print(b.String())
	return nil
}
