[project]
  name = "SyncDatabox/nicmac/projects/ateam-base"
  default_profile = ""
  keychain_key = "SyncDatabox/nicmac/projects/ateam-base-71df3a"

[git]
  repo = ""
  remote_origin_url = "git@github.com-voidexpr:voidexpr/ateam.git"

[report]
  max_parallel = 3
  report_timeout_minutes = 20

[review]
  timeout_minutes = 20

[code]
  timeout_minutes = 120

[run]
  timeout_minutes = 60

[serve]
  port = 0

[roles]
  automation = "off"
  basic_project_structure = "off"
  "code.bugs" = "off"
  "code.recent" = "off"
  "code.structure" = "off"
  "critic.engineering" = "off"
  "critic.features" = "off"
  "critic.project" = "off"
  critic_engineering = "off"
  critic_project = "off"
  "database.schema" = "off"
  database_config = "off"
  database_schema = "on"
  dependencies = "on"
  "design.architecture" = "off"
  "docs.external" = "off"
  "docs.followable" = "off"
  "docs.internal" = "off"
  docs_external = "on"
  docs_internal = "on"
  "perf.benchmarks" = "off"
  "perf.optimization" = "off"
  production_ready = "off"
  "project.automation" = "off"
  "project.dependencies" = "off"
  "project.maintenance" = "off"
  "project.production_ready" = "off"
  "project.security" = "off"
  project_characteristics = "on"
  refactor_architecture = "off"
  refactor_small = "on"
  security = "on"
  shortcut_taker = "off"
  "test.blackbox" = "off"
  "test.gaps" = "off"
  "test.quality" = "off"
  "test.recent" = "off"
  testing_basic = "on"
  testing_full = "off"

[supervisor]
  default_profile = ""
  review_profile = ""
  code_profile = ""
  code_supervisor_profile = ""

[profiles]

[sandbox-extra]

[container-extra]
